### ISSUE TITLE
Checklist for Michelle

### ISSUE THREAD

**Issue by collinmmckinney** [DartDraw/DartDraw#100]
- [ ] Add to ContextualMenuContainer: onResizeShapeTo(width, height), onMoveShapeTo(x, y), onRotateShapeTo(angle) in mapDispatchToProps. Instead of `dispatch`, just add a console.log statement to log the arguments.

- [ ] Add those functions as props of ContextualMenu

- [ ] Pass those functions into RectangleMenu as props, add those functions to the props of RectangleMenu

- [ ] In RectangleMenu, call those functions when the input changes

When that is working:

- [ ] Add a Redux action to actions/menu.js for each of the functions (just console.log the arguments) import into ContextualMenuContainer and use dispatch.

- [ ] When console.log is working, return an action, e.g. MOVE_SHAPE_TO with a payload of payload: { x, y }

- [ ] Now the action should be sending to the reducer. In reducers/drawingState, add MOVE_SHAPE_TO to the switch statement, and console.log action.payload.

- [ ] When that's working, check out reducers/caseFunctions/shape.js. This is where the functions moveShapeTo, rotateShapeTo, etc. are being called with a keyboard shortcuts. You want to make a new caseFunction, for example, moveShapeTo, (in the same file) that uses those functions in the same way.

- [ ] Now, from the reducer, call your case function and assign the return to value to updatedState.
